-- Add some seed job specifications for testing
INSERT INTO public.job_specifications (
  id,
  title,
  company_name,
  status,
  short_description,
  primary_skills,
  experience_years_min,
  experience_years_max,
  preferred_location,
  working_mode,
  salary_base_low,
  salary_base_high,
  created_at,
  updated_at
) VALUES 
(
  '42a98bc2-41cc-48f2-83b8-f207f65add05',
  'Senior Software Engineer',
  'Acme Corp',
  'confirmed',
  'We are looking for a Senior Software Engineer to join our growing team. The ideal candidate will have strong experience in full-stack development and a passion for building scalable applications.',
  ARRAY['JavaScript', 'React', 'Node.js', 'TypeScript', 'PostgreSQL'],
  5,
  8,
  'Remote',
  'Hybrid',
  120000,
  160000,
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'Product Designer',
  'TechStart Inc',
  'confirmed',
  'Seeking a creative Product Designer to lead user experience initiatives and create intuitive, user-centered designs for our SaaS platform.',
  ARRAY['Figma', 'UI/UX Design', 'User Research', 'Prototyping', 'Design Systems'],
  3,
  6,
  'San Francisco, CA',
  'Hybrid',
  90000,
  130000,
  '2024-01-20T14:30:00Z',
  '2024-01-20T14:30:00Z'
),
(
  gen_random_uuid(),
  'Marketing Manager',
  'Global Solutions Ltd',
  'draft',
  'Looking for an experienced Marketing Manager to develop and execute comprehensive marketing strategies that drive growth and brand awareness.',
  ARRAY['Digital Marketing', 'SEO/SEM', 'Content Strategy', 'Analytics', 'Brand Management'],
  4,
  7,
  'New York, NY',
  'In-office',
  80000,
  110000,
  '2024-01-22T16:45:00Z',
  '2024-01-22T16:45:00Z'
);