// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffzmfiijgszfskqdugvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmem1maWlqZ3N6ZnNrcWR1Z3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0OTY3ODksImV4cCI6MjA1NjA3Mjc4OX0.aOW8fekZcpfUVT6OG3gb5uiyxTXyLxFVqGpv7UGphdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);